<?php

/**
 * BaseCobrador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $apellido
 * @property Doctrine_Collection $Cobranzas
 * 
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getApellido()  Returns the current record's "apellido" value
 * @method Doctrine_Collection getCobranzas() Returns the current record's "Cobranzas" collection
 * @method Cobrador            setNombre()    Sets the current record's "nombre" value
 * @method Cobrador            setApellido()  Sets the current record's "apellido" value
 * @method Cobrador            setCobranzas() Sets the current record's "Cobranzas" collection
 * 
 * @package    subsecretaria
 * @subpackage model
 * @author     Manuel De la Penna
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCobrador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cobrador');
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('apellido', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cobranza as Cobranzas', array(
             'local' => 'id',
             'foreign' => 'cobrador_id'));
    }
}