<?php

/**
 * BaseCobranzaAutomatica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mes
 * @property integer $anio
 * @property integer $valor_cuota
 * @property integer $valor_cuota_descuento
 * @property boolean $generada
 * 
 * @method integer            getMes()                   Returns the current record's "mes" value
 * @method integer            getAnio()                  Returns the current record's "anio" value
 * @method integer            getValorCuota()            Returns the current record's "valor_cuota" value
 * @method integer            getValorCuotaDescuento()   Returns the current record's "valor_cuota_descuento" value
 * @method boolean            getGenerada()              Returns the current record's "generada" value
 * @method CobranzaAutomatica setMes()                   Sets the current record's "mes" value
 * @method CobranzaAutomatica setAnio()                  Sets the current record's "anio" value
 * @method CobranzaAutomatica setValorCuota()            Sets the current record's "valor_cuota" value
 * @method CobranzaAutomatica setValorCuotaDescuento()   Sets the current record's "valor_cuota_descuento" value
 * @method CobranzaAutomatica setGenerada()              Sets the current record's "generada" value
 * 
 * @package    subsecretaria
 * @subpackage model
 * @author     Manuel De la Penna
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCobranzaAutomatica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cobranza_automatica');
        $this->hasColumn('mes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('anio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('valor_cuota', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('valor_cuota_descuento', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('generada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}