<?php

/**
 * BaseCuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $socio_id
 * @property integer $mes
 * @property integer $anio
 * @property integer $monto
 * @property boolean $pagada
 * @property Socio $Socio
 * @property Doctrine_Collection $Cobranzas
 * 
 * @method integer             getSocioId()   Returns the current record's "socio_id" value
 * @method integer             getMes()       Returns the current record's "mes" value
 * @method integer             getAnio()      Returns the current record's "anio" value
 * @method integer             getMonto()     Returns the current record's "monto" value
 * @method boolean             getPagada()    Returns the current record's "pagada" value
 * @method Socio               getSocio()     Returns the current record's "Socio" value
 * @method Doctrine_Collection getCobranzas() Returns the current record's "Cobranzas" collection
 * @method Cuota               setSocioId()   Sets the current record's "socio_id" value
 * @method Cuota               setMes()       Sets the current record's "mes" value
 * @method Cuota               setAnio()      Sets the current record's "anio" value
 * @method Cuota               setMonto()     Sets the current record's "monto" value
 * @method Cuota               setPagada()    Sets the current record's "pagada" value
 * @method Cuota               setSocio()     Sets the current record's "Socio" value
 * @method Cuota               setCobranzas() Sets the current record's "Cobranzas" collection
 * 
 * @package    subsecretaria
 * @subpackage model
 * @author     Manuel De la Penna
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCuota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuota');
        $this->hasColumn('socio_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('anio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('monto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pagada', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Socio', array(
             'local' => 'socio_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Cobranza as Cobranzas', array(
             'local' => 'id',
             'foreign' => 'cuota_id'));
    }
}