<?php

/**
 * BaseCobranza
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property integer $cobrador_id
 * @property integer $lugar_cobro_id
 * @property integer $cuota_id
 * @property Cobrador $Cobrador
 * @property LugarCobro $LugarCobro
 * @property Cuota $Cuota
 * 
 * @method date       getFecha()          Returns the current record's "fecha" value
 * @method integer    getCobradorId()     Returns the current record's "cobrador_id" value
 * @method integer    getLugarCobroId()   Returns the current record's "lugar_cobro_id" value
 * @method integer    getCuotaId()        Returns the current record's "cuota_id" value
 * @method Cobrador   getCobrador()       Returns the current record's "Cobrador" value
 * @method LugarCobro getLugarCobro()     Returns the current record's "LugarCobro" value
 * @method Cuota      getCuota()          Returns the current record's "Cuota" value
 * @method Cobranza   setFecha()          Sets the current record's "fecha" value
 * @method Cobranza   setCobradorId()     Sets the current record's "cobrador_id" value
 * @method Cobranza   setLugarCobroId()   Sets the current record's "lugar_cobro_id" value
 * @method Cobranza   setCuotaId()        Sets the current record's "cuota_id" value
 * @method Cobranza   setCobrador()       Sets the current record's "Cobrador" value
 * @method Cobranza   setLugarCobro()     Sets the current record's "LugarCobro" value
 * @method Cobranza   setCuota()          Sets the current record's "Cuota" value
 * 
 * @package    subsecretaria
 * @subpackage model
 * @author     Manuel De la Penna
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCobranza extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cobranza');
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('cobrador_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lugar_cobro_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cuota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cobrador', array(
             'local' => 'cobrador_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('LugarCobro', array(
             'local' => 'lugar_cobro_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Cuota', array(
             'local' => 'cuota_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}