lugar_cobro:
  class: sfDoctrineRouteCollection
  options:
    model:                LugarCobro
    module:               lugarCobro
    prefix_path:          /lugarCobro
    column:               id
    with_wildcard_routes: true

valor_cuota:
  class: sfDoctrineRouteCollection
  options:
    model:                ValorCuota
    module:               valorCuota
    prefix_path:          /valorCuota
    column:               id
    with_wildcard_routes: true

cobrador:
  class: sfDoctrineRouteCollection
  options:
    model:                Cobrador
    module:               cobrador
    prefix_path:          /cobrador
    column:               id
    with_wildcard_routes: true

tipo_guarda_tipoGuarda:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoGuarda
    module:               tipoGuarda
    prefix_path:          /tipoGuarda
    column:               id
    with_wildcard_routes: true

titular_guarda:
  class: sfDoctrineRouteCollection
  options:
    model:                TitularGuarda
    module:               titularGuarda
    prefix_path:          /titularGuarda
    column:               id
    with_wildcard_routes: true

tipo_guarda:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoGuarda
    module:               tipoguarda
    prefix_path:          /tipoguarda
    column:               id
    with_wildcard_routes: true

opcion_entrevista:
  class: sfDoctrineRouteCollection
  options:
    model:                OpcionEntrevista
    module:               opcionEntrevista
    prefix_path:          /opcionEntrevista
    column:               id
    with_wildcard_routes: true

opcion_intervencion:
  class: sfDoctrineRouteCollection
  options:
    model:                OpcionIntervencion
    module:               opcionIntervencion
    prefix_path:          /opcionIntervencion
    column:               id
    with_wildcard_routes: true

organismo:
  class: sfDoctrineRouteCollection
  options:
    model:                Organismo
    module:               organismo
    prefix_path:          /organismo
    column:               id
    with_wildcard_routes: true

vinculo_relacion_jefe_hogar:
  class: sfDoctrineRouteCollection
  options:
    model:                VinculoRelacionJefeHogar
    module:               vinculoRelacionJefeHogar
    prefix_path:          /vinculoRelacionJefeHogar
    column:               id
    with_wildcard_routes: true

asesoria_incapaces_denuncia:
  class: sfDoctrineRouteCollection
  options:
    model:                AsesoriaIncapacesDenuncia
    module:               asesoriaIncapacesDenuncia
    prefix_path:          /asesoriaIncapacesDenuncia
    column:               id
    with_wildcard_routes: true

motivo_egreso_lugar_alojamiento:
  class: sfDoctrineRouteCollection
  options:
    model:                MotivoEgresoLugarAlojamiento
    module:               motivoEgresoLugarAlojamiento
    prefix_path:          /motivoEgresoLugarAlojamiento
    column:               id
    with_wildcard_routes: true

motivo_fuero_familia:
  class: sfDoctrineRouteCollection
  options:
    model:                MotivoFueroFamilia
    module:               motivoFueroFamilia
    prefix_path:          /motivoFueroFamilia
    column:               id
    with_wildcard_routes: true

final_medida_abrigo:
  class: sfDoctrineRouteCollection
  options:
    model:                FinalMedidaAbrigo
    module:               finalMedidaAbrigo
    prefix_path:          /finalMedidaAbrigo
    column:               id
    with_wildcard_routes: true

asesoria_incapaces_medida_abrigo:
  class: sfDoctrineRouteCollection
  options:
    model:                AsesoriaIncapacesMedidaAbrigo
    module:               asesoriaIncapacesMedidaAbrigo
    prefix_path:          /asesoriaIncapacesMedidaAbrigo
    column:               id
    with_wildcard_routes: true

control_legalidad_medida_abrigo:
  class: sfDoctrineRouteCollection
  options:
    model:                ControlLegalidadMedidaAbrigo
    module:               controlLegalidadMedidaAbrigo
    prefix_path:          /controlLegalidadMedidaAbrigo
    column:               id
    with_wildcard_routes: true

lugar_ejecucion_medida_abrigo:
  class: sfDoctrineRouteCollection
  options:
    model:                LugarEjecucionMedidaAbrigo
    module:               lugarEjecucionMedidaAbrigo
    prefix_path:          /lugarEjecucionMedidaAbrigo
    column:               id
    with_wildcard_routes: true

motivo_medida_abrigo:
  class: sfDoctrineRouteCollection
  options:
    model:                MotivoMedidaAbrigo
    module:               motivoMedidaAbrigo
    prefix_path:          /motivoMedidaAbrigo
    column:               id
    with_wildcard_routes: true

area_solicitud_medida_abrigo:
  class: sfDoctrineRouteCollection
  options:
    model:                AreaSolicitudMedidaAbrigo
    module:               areaSolicitudMedidaAbrigo
    prefix_path:          /areaSolicitudMedidaAbrigo
    column:               id
    with_wildcard_routes: true

area_articulacion:
  class: sfDoctrineRouteCollection
  options:
    model:                AreaArticulacion
    module:               areaArticulacion
    prefix_path:          /areaArticulacion
    column:               id
    with_wildcard_routes: true

medida_cautelar:
  class: sfDoctrineRouteCollection
  options:
    model:                MedidaCautelar
    module:               medidaCautelar
    prefix_path:          /medidaCautelar
    column:               id
    with_wildcard_routes: true

hogar:
  class: sfDoctrineRouteCollection
  options:
    model:                Hogar
    module:               hogar
    prefix_path:          /hogar
    column:               id
    with_wildcard_routes: true

categoria_hogar:
  class: sfDoctrineRouteCollection
  options:
    model:                CategoriaHogar
    module:               categoriaHogar
    prefix_path:          /categoriaHogar
    column:               id
    with_wildcard_routes: true

momento:
  class: sfDoctrineRouteCollection
  options:
    model:                Momento
    module:               momento
    prefix_path:          /momento
    column:               id
    with_wildcard_routes: true

pension_nacional:
  class: sfDoctrineRouteCollection
  options:
    model:                PensionNacional
    module:               pension_nacional
    prefix_path:          /pension_nacional
    column:               id
    with_wildcard_routes: true

pension_provincial:
  class: sfDoctrineRouteCollection
  options:
    model:                PensionProvincial
    module:               pension_provincial
    prefix_path:          /pension_provincial
    column:               id
    with_wildcard_routes: true

plan_social:
  class: sfDoctrineRouteCollection
  options:
    model:                PlanSocial
    module:               plan_social
    prefix_path:          /plan_social
    column:               id
    with_wildcard_routes: true

turno:
  class: sfDoctrineRouteCollection
  options:
    model:                Turno
    module:               turno
    prefix_path:          /turno
    column:               id
    with_wildcard_routes: true

escuela:
  class: sfDoctrineRouteCollection
  options:
    model:                Escuela
    module:               escuela
    prefix_path:          /escuela
    column:               id
    with_wildcard_routes: true

escolaridad:
  class: sfDoctrineRouteCollection
  options:
    model:                Escolaridad
    module:               escolaridad
    prefix_path:          /escolaridad
    column:               id
    with_wildcard_routes: true

condicion_laboral:
  class: sfDoctrineRouteCollection
  options:
    model:                CondicionLaboral
    module:               condicion_laboral
    prefix_path:          /condicion_laboral
    column:               id
    with_wildcard_routes: true

documentacion:
  class: sfDoctrineRouteCollection
  options:
    model:                Documentacion
    module:               documentacion
    prefix_path:          /documentacion
    column:               id
    with_wildcard_routes: true

localidad:
  class: sfDoctrineRouteCollection
  options:
    model:                Localidad
    module:               localidad
    prefix_path:          /localidad
    column:               id
    with_wildcard_routes: true

barrio:
  class: sfDoctrineRouteCollection
  options:
    model:                Barrio
    module:               barrio
    prefix_path:          /barrio
    column:               id
    with_wildcard_routes: true

genero:
  class: sfDoctrineRouteCollection
  options:
    model:                Genero
    module:               genero
    prefix_path:          /genero
    column:               id
    with_wildcard_routes: true

vinculo:
  class: sfDoctrineRouteCollection
  options:
    model:                Vinculo
    module:               vinculo
    prefix_path:          /vinculo
    column:               id
    with_wildcard_routes: true

situacion_vulneracion:
  class: sfDoctrineRouteCollection
  options:
    model:                SituacionVulneracion
    module:               situacion_vulneracion
    prefix_path:          /situacion_vulneracion
    column:               id
    with_wildcard_routes: true

categoria_vulneracion:
  class: sfDoctrineRouteCollection
  options:
    model:                CategoriaVulneracion
    module:               categoria_vulneracion
    prefix_path:          /categoria_vulneracion
    column:               id
    with_wildcard_routes: true

ingresante:
  class: sfDoctrineRouteCollection
  options:
    model:                Ingresante
    module:               ingresante
    prefix_path:          /ingresante
    column:               id
    with_wildcard_routes: true

situacion_vulneracion_expediente:
  class: sfDoctrineRouteCollection
  options:
    model:                SituacionVulneracionExpediente
    module:               situacion_vulneracion_expediente
    prefix_path:          /situacion_vulneracion_expediente
    column:               id
    with_wildcard_routes: true

categoria_vulneracion_expediente:
  class: sfDoctrineRouteCollection
  options:
    model:                CategoriaVulneracionExpediente
    module:               categoria_vulneracion_expediente
    prefix_path:          /categoria_vulneracion_expediente
    column:               id
    with_wildcard_routes: true

equipo:
  class: sfDoctrineRouteCollection
  options:
    model:                Equipo
    module:               equipo
    prefix_path:          /equipo
    column:               id
    with_wildcard_routes: true

group:
  class: sfDoctrineRouteCollection
  options:
    model:                Group
    module:               groups
    prefix_path:          /groups
    column:               id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               users
    prefix_path:          /users
    column:               id
    with_wildcard_routes: true

modo_ingreso:
  class: sfDoctrineRouteCollection
  options:
    model:                ModoIngreso
    module:               modoIngreso
    prefix_path:          /modoIngreso
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# default rules
homepage:
  url:   /
  param: { module: index, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
