<?php

/**
 * CobradorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CobradorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CobradorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cobrador');
    }
}