<?php

/**
 * CobranzaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CobranzaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CobranzaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cobranza');
    }
}