<?php

/**
 * Cuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    subsecretaria
 * @subpackage model
 * @author     Manuel De la Penna
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cuota extends BaseCuota
{
  public function __toString()
  {
    return $this->getMes(). '/'.$this->getAnio();
  }

}