<?php

/**
 * CuotaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuotaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuotaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cuota');
    }
}