<?php

/**
 * LugarCobroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugarCobroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LugarCobroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LugarCobro');
    }
}