<?php

/**
 * Socio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    subsecretaria
 * @subpackage model
 * @author     Manuel De la Penna
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Socio extends BaseSocio
{
  public function getCantidadCuotasAdelantadas()
  {
	$anio = date('Y');
	$mes = date('n');
    $q= Doctrine_Query::create()
            ->select('*, count(s.id) as cantidad')
            ->from('Socio s')
            ->innerJoin('s.Cuotas')
			->where('s.id = ?', $this->getId())
            ->andWhere('s.Cuotas.pagada = ?', true)
			->andWhere("(s.Cuotas.anio = $anio and s.Cuotas.mes > $mes) or (s.Cuotas.anio > $anio)")
			->groupBy('s.id');
			
	$result = $q->execute();
	
	if (count($result)>0){
		$result = $result[0];
		return $result->getCantidad();
	}
    
	return 0;	
    
  }  
}