<?php

/**
 * SocioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SocioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SocioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Socio');
    }
    
    public static function getConDeuda()
    {
        
        return Doctrine_Query::create()
                ->select('*, sum(s.Cuotas.monto) as total')
                ->from('Socio s')
                ->innerJoin('s.Cuotas')
                ->where('s.Cuotas.pagada = ?', false)
                ->groupBy('s.id');
                
    }
}