# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Biblioteca Popular y Centro Cultural José Ingenieros
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, style.css, expediente.css, redmond/jquery-ui-1.8.15.custom.css, menu.css, jquery.alerts.css, alerts.css, formulario.css]

  javascripts:    [jquery-1.5.1.min.js, jquery-ui-1.8.14.custom.min.js,jquery.ui.datepicker-es.js, menu.js, jquery.alerts.js, tiny_mce/tiny_mce.js]

  has_layout:     true
  layout:         layout
