generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LugarCobro
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lugar_cobro
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de lugares de cobro
        batch_actions: []
        display: [nombre]
      filter:  ~
      form:    ~
      edit:
        title: Editar lugar de cobro
      new:
        title: Nuevo lugar de cobro
